#!/bin/bash

for var in {1..28}
do
	peer chaincode invoke -o orderer0.example.com:7050 -n thermal_modify -c '{"Args":["initThermal","Brown","01012345678","'$var'","2011251840","36.6"]}' -C channel1
done

for var in {29..2800}
do
	peer chaincode invoke -o orderer0.example.com:7050 -n thermal_modify -c '{"Args":["initThermal","Joe","01012345678","'$var'","2011251840","36.6"]}' -C channel1
done
